In [ ]:
### Preprocessing Data
# 1. data formatting
# 2. data cleaning
# 3. data sampling
### Begin the feature engineering
## transform the preprocessed data
# 1. Scaling
# 2. Decomposition
# 3. Aggregation

In [1]:
from sklearn import preprocessing as pp
import numpy as np
x = np.array([[1.,-2.,2.], [3.,0.,0.], [0.,1.,-1]])
x

array([[ 1., -2.,  2.],
       [ 3.,  0.,  0.],
       [ 0.,  1., -1.]])

In [2]:
x_scaled = pp.scale(x)
x_scaled

array([[-0.26726124, -1.33630621,  1.33630621],
       [ 1.33630621,  0.26726124, -0.26726124],
       [-1.06904497,  1.06904497, -1.06904497]])

In [3]:
x_scaled.mean(axis=0)

array([7.40148683e-17, 0.00000000e+00, 0.00000000e+00])

In [4]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [5]:
# normalize features
pp.normalize(x, norm='l1')

array([[ 0.2, -0.4,  0.4],
       [ 1. ,  0. ,  0. ],
       [ 0. ,  0.5, -0.5]])

In [6]:
pp.normalize(x, norm='l2')

array([[ 0.33333333, -0.66666667,  0.66666667],
       [ 1.        ,  0.        ,  0.        ],
       [ 0.        ,  0.70710678, -0.70710678]])